version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region eu-central-1)
      - echo Docker version...
      - docker version
      - echo repo name [$IMAGE_REPO_NAME]
      - echo image tag [$IMAGE_TAG]
      - echo AWS Account ID [$AWS_ACCOUNT_ID]
      - echo AWS region [$AWS_DEFAULT_REGION]
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t python-dev .
      - docker tag python-dev:latest 362546943964.dkr.ecr.eu-central-1.amazonaws.com/python-dev:latest
      - docker tag python-dev:latest 362546943964.dkr.ecr.eu-central-1.amazonaws.com/python-dev:$CODEBUILD_START_TIME
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 362546943964.dkr.ecr.eu-central-1.amazonaws.com/python-dev:latest
      - docker push 362546943964.dkr.ecr.eu-central-1.amazonaws.com/python-dev:$CODEBUILD_START_TIME
