version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region eu-central-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t python-dev:$IMAGE_TAG -t python-dev:latest -f Dockerfile .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 362546943964.dkr.ecr.eu-central-1.amazonaws.com/python-dev:latest
      - docker push 362546943964.dkr.ecr.eu-central-1.amazonaws.com/python-dev:$IMAGE_TAG